version: '3.8'
services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - psql
    networks:
      - zti

  psql:
    image: postgres:16.2
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - zti

volumes:
  db_data:
    driver: local

networks:
  zti:
    driver: bridge
    external: true